### PR TITLE
Time out waiting on SSH connection gracefully, use asyncio on receiving end.

### PR DESCRIPTION
**Pull request by belitskiy**

### CODE REVIEW

**Comment by MichaelHudgins** [comment]
Which PR are you using to run jobs to test this?

**Comment by belitskiy** [comment]
> Which PR are you using to run jobs to test this?

https://github.com/google-ml-infra/jax-fork/pull/26

**Comment by MichaelHudgins** [comment]
Could you add an action to this repo that listens for the labels for testing purposes?  This repo has the same runners available to it.

**Comment by belitskiy** [comment]
> Could you add a workflow to this repo that listens for the labels for testing purposes? This repo has the same runners available to it.

https://github.com/google-ml-infra/actions/pull/7

**Comment by MichaelHudgins** [comment]
> > Could you add a workflow to this repo that listens for the labels for testing purposes? This repo has the same runners available to it.
> 
> #7

Approved it, i'll give this one a try with that merged

**Pull request merged**
